let nome = prompt("Olá, Boa noite! Qual é o seu nome?")
alert("Olá! " + nome + "!!")
let question = prompt("Como posso ajudar você esta noite?")
alert("Ok aguarde um minuto!, irei solucionar seu problema")
let send = prompt("Diga a ela, que a ama, e que está morrendo de Saudade, tenho certeza que ela está também!")
alert("Sei que ela irá amar, pois foram feitos um para o outro!")
let otherAsk = prompt("Mais alguma coisa que você precisa?")
alert("Então ok, termino meu atendimento aqui, tenha uma boa noite! ")